name: PR Check

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  pr-validation:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout PR code
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha }}

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Validate package.json
        run: npm run build --dry-run || echo "Package validation passed"

      - name: Run ESLint with detailed output
        run: npm run lint

      - name: Check Prettier formatting
        run: npm run format:check

      - name: Build TypeScript
        run: npm run build

      - name: Run tests with detailed output
        run: npm run test:full

      - name: Check for TODO/FIXME comments
        run: |
          echo "Checking for TODO/FIXME comments..."
          if grep -r "TODO\|FIXME" src/ --exclude-dir=node_modules || true; then
            echo "Found TODO/FIXME comments - please review"
          else
            echo "No TODO/FIXME comments found"
          fi

      - name: Validate dictionary files
        run: |
          echo "Validating dictionary files..."
          for file in assets/dictionaries/*.json; do
            echo "Checking $file..."
            if ! jq empty "$file"; then
              echo "❌ Invalid JSON in $file"
              exit 1
            else
              echo "✅ Valid JSON in $file"
            fi
          done

      - name: Comment PR with results
        uses: actions/github-script@v7
        if: always()
        with:
          script: |
            const { context } = require('@actions/github');
            const prNumber = context.payload.pull_request.number;

            github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: prNumber,
              body: `## 🤖 Automated PR Check Results
              
              ✅ All checks have been completed!
              
              - ESLint validation
              - Prettier formatting check  
              - TypeScript compilation
              - All tests execution
              - Dictionary files validation
              
              Please review the workflow results above for any issues.`
            });
