name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Run quality checks
        run: npm run check

      - name: Run all tests
        run: npm run test:full

      - name: Build for release
        run: npm run build

      - name: Build executables
        run: npm run build:exe:all

      - name: Copy assets and keyservers for Unix
        run: |
          cp -r assets build/
          cp node_modules/node-global-key-listener/bin/WinKeyServer.exe build/ || true
          cp node_modules/node-global-key-listener/bin/X11KeyServer build/ || true  
          cp node_modules/node-global-key-listener/bin/MacKeyServer build/ || true

      - name: Create Windows Release Archive
        run: |
          mkdir -p release-windows
          cp build/node-layout-switcher-win.exe release-windows/
          cp -r build/assets release-windows/
          cp build/WinKeyServer.exe release-windows/ || true
          cp README.md LICENSE release-windows/
          cd release-windows && zip -r ../node-layout-switcher-${{ github.ref_name }}-windows.zip .

      - name: Create Unix Release Archive
        run: |
          mkdir -p release-unix
          cp build/node-layout-switcher-linux release-unix/
          cp build/node-layout-switcher-macos release-unix/
          cp -r build/assets release-unix/
          cp build/X11KeyServer release-unix/ || true
          cp build/MacKeyServer release-unix/ || true
          cp README.md LICENSE release-unix/
          tar -czf node-layout-switcher-${{ github.ref_name }}-unix.tar.gz -C release-unix .

      - name: Create Source Archive
        run: |
          tar -czf node-layout-switcher-${{ github.ref_name }}-source.tar.gz \
            dist/ \
            assets/ \
            package.json \
            README.md \
            LICENSE

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            node-layout-switcher-${{ github.ref_name }}-windows.zip
            node-layout-switcher-${{ github.ref_name }}-unix.tar.gz
            node-layout-switcher-${{ github.ref_name }}-source.tar.gz
          generate_release_notes: true
          draft: false
          prerelease: ${{ contains(github.ref_name, 'beta') || contains(github.ref_name, 'alpha') }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  npm-publish:
    runs-on: ubuntu-latest
    needs: release
    if: ${{ !contains(github.ref_name, 'beta') && !contains(github.ref_name, 'alpha') }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          registry-url: 'https://registry.npmjs.org'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build package
        run: npm run build

      - name: Publish to NPM
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
