name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Run quality checks
        run: npm run check

      - name: Run all tests
        run: npm run test:full

      - name: Build for release
        run: npm run build

      - name: Create Release Archive
        run: |
          tar -czf node-layout-switcher-${{ github.ref_name }}.tar.gz \
            dist/ \
            assets/ \
            package.json \
            README.md \
            LICENSE

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            node-layout-switcher-${{ github.ref_name }}.tar.gz
          generate_release_notes: true
          draft: false
          prerelease: ${{ contains(github.ref_name, 'beta') || contains(github.ref_name, 'alpha') }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  npm-publish:
    runs-on: ubuntu-latest
    needs: release
    if: ${{ !contains(github.ref_name, 'beta') && !contains(github.ref_name, 'alpha') }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          registry-url: 'https://registry.npmjs.org'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build package
        run: npm run build

      - name: Publish to NPM
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
